### ISSUE TITLE
install.php not reachable

### ISSUE THREAD

**Issue by jumblies** [Starttoaster/docker-traefik#3]
Thanks for the script.  
Traefik works fine.  
For this docker image of dokuwiki, How do you set up the admin and ACL since install.php isn't available?

**Comment by Starttoaster** [comment]
Thanks! And that doesn't seem right. The install page has been available to me in the past with this image at: https://sub.domain.tld/install.php

**Comment by Starttoaster** [comment]
I just gave it a go again through this script and it appears fine for me. If you're still having this issue, could you please give me information such as: 
What distro are you using? 
What is the output of: `cat /etc/selinux/conf` 
What is the output of: `docker logs dokuwiki`

The DokuWiki website gives some installation related debugging help as well here: https://www.dokuwiki.org/installer

**Comment by jumblies** [comment]
I got it figured out.  It was persistent volumes that prevented a clean new container.  one of the perils of docker-compose up  and ctrl-c.  I appreciate your help.

**Comment by Starttoaster** [comment]
Glad you got it working!
