### ISSUE TITLE
Any schedule about V2?

### ISSUE THREAD

**Issue by thepenguinthatwants** [Starttoaster/docker-traefik#7]
Hi!

You were the one that I've learned from how to use Traefik from. And I feel like owing you a lot.

I was wondering if you have possibly any time estimation about the release of V2? Just out of curiosity.

**Comment by Starttoaster** [comment]
Hey! Thank you for the question. I was focusing more on work assignments recently than this. But since you asked, I gather there is interest in me getting v2 finished, so I will do so. Sorry for the wait! I'll have time this weekend to get it done.

**Comment by Starttoaster** [comment]
As an update: I have the v2 configuration files working on my own server now, which means I'll be able to update the script soon. I won't get to it today as projected, but I'll work on it this week and probably have a barebones configuration here by Tuesday morning for just basic Traefik v2 and an example container image with labels.

**Comment by Starttoaster** [comment]
Created branch [traefik-v2](https://github.com/Starttoaster/docker-traefik/tree/traefik-v2) for the same. Currently has a basic working configuration that I have tested.

**Comment by thepenguinthatwants** [comment]
Hi!
Do you have any idea how to make the traefik dashboard to show up?
The traefik.yml contains
api:
  dashboard: true

but localhost with browser only shows `404 page not found`
